//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ililce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilce
    {
        public int ilceid { get; set; }
        public string ilcead { get; set; }
        public Nullable<int> ilid { get; set; }
    
        public virtual İl İl { get; set; }
    }
}
