//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ililce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldeneme
    {
        public int Id { get; set; }
        public string İl { get; set; }
        public string İlce { get; set; }
    }
}
